//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gyak7_jlv3dc.mnb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrenciesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrenciesResult {
            get {
                return this.GetCurrenciesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrenciesResultField, value) != true)) {
                    this.GetCurrenciesResultField = value;
                    this.RaisePropertyChanged("GetCurrenciesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrencyUnitsResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrencyUnitsResult {
            get {
                return this.GetCurrencyUnitsResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrencyUnitsResultField, value) != true)) {
                    this.GetCurrencyUnitsResultField = value;
                    this.RaisePropertyChanged("GetCurrencyUnitsResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrentExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrentExchangeRatesResult {
            get {
                return this.GetCurrentExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrentExchangeRatesResultField, value) != true)) {
                    this.GetCurrentExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetCurrentExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetDateIntervalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetDateIntervalResult {
            get {
                return this.GetDateIntervalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetDateIntervalResultField, value) != true)) {
                    this.GetDateIntervalResultField = value;
                    this.RaisePropertyChanged("GetDateIntervalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((object.ReferenceEquals(this.startDateField, value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((object.ReferenceEquals(this.endDateField, value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetExchangeRatesResult {
            get {
                return this.GetExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetExchangeRatesResultField, value) != true)) {
                    this.GetExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetInfoResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetInfoResult {
            get {
                return this.GetInfoResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetInfoResultField, value) != true)) {
                    this.GetInfoResultField = value;
                    this.RaisePropertyChanged("GetInfoResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="mnb.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetCurrenciesResponse GetCurrencies(gyak7_jlv3dc.mnb.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrenciesResponse> GetCurrenciesAsync(gyak7_jlv3dc.mnb.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse GetCurrencyUnits(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin" +
            "gFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetDateIntervalResponse GetDateInterval(gyak7_jlv3dc.mnb.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetDateIntervalResponse> GetDateIntervalAsync(gyak7_jlv3dc.mnb.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetExchangeRatesResponse GetExchangeRates(gyak7_jlv3dc.mnb.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetExchangeRatesResponse> GetExchangeRatesAsync(gyak7_jlv3dc.mnb.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        gyak7_jlv3dc.mnb.GetInfoResponse GetInfo(gyak7_jlv3dc.mnb.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetInfoResponse> GetInfoAsync(gyak7_jlv3dc.mnb.GetInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrenciesRequestBody GetCurrencies;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(gyak7_jlv3dc.mnb.GetCurrenciesRequestBody GetCurrencies) {
            this.GetCurrencies = GetCurrencies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrenciesResponseBody GetCurrenciesResponse1;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(gyak7_jlv3dc.mnb.GetCurrenciesResponseBody GetCurrenciesResponse1) {
            this.GetCurrenciesResponse1 = GetCurrenciesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrencyUnitsRequestBody GetCurrencyUnits;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            this.GetCurrencyUnits = GetCurrencyUnits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(gyak7_jlv3dc.mnb.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1) {
            this.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            this.GetCurrentExchangeRates = GetCurrentExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1) {
            this.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetDateIntervalRequestBody GetDateInterval;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(gyak7_jlv3dc.mnb.GetDateIntervalRequestBody GetDateInterval) {
            this.GetDateInterval = GetDateInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetDateIntervalResponseBody GetDateIntervalResponse1;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(gyak7_jlv3dc.mnb.GetDateIntervalResponseBody GetDateIntervalResponse1) {
            this.GetDateIntervalResponse1 = GetDateIntervalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetExchangeRatesRequestBody GetExchangeRates;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(gyak7_jlv3dc.mnb.GetExchangeRatesRequestBody GetExchangeRates) {
            this.GetExchangeRates = GetExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetExchangeRatesResponseBody GetExchangeRatesResponse1;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(gyak7_jlv3dc.mnb.GetExchangeRatesResponseBody GetExchangeRatesResponse1) {
            this.GetExchangeRatesResponse1 = GetExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetInfoRequestBody GetInfo;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(gyak7_jlv3dc.mnb.GetInfoRequestBody GetInfo) {
            this.GetInfo = GetInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public gyak7_jlv3dc.mnb.GetInfoResponseBody GetInfoResponse1;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(gyak7_jlv3dc.mnb.GetInfoResponseBody GetInfoResponse1) {
            this.GetInfoResponse1 = GetInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap>, gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetCurrenciesResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrencies(gyak7_jlv3dc.mnb.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public gyak7_jlv3dc.mnb.GetCurrenciesResponseBody GetCurrencies(gyak7_jlv3dc.mnb.GetCurrenciesRequestBody GetCurrencies1) {
            gyak7_jlv3dc.mnb.GetCurrenciesRequest inValue = new gyak7_jlv3dc.mnb.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies1;
            gyak7_jlv3dc.mnb.GetCurrenciesResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.GetCurrenciesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrenciesResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrenciesAsync(gyak7_jlv3dc.mnb.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrenciesResponse> GetCurrenciesAsync(gyak7_jlv3dc.mnb.GetCurrenciesRequestBody GetCurrencies) {
            gyak7_jlv3dc.mnb.GetCurrenciesRequest inValue = new gyak7_jlv3dc.mnb.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrencyUnits(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public gyak7_jlv3dc.mnb.GetCurrencyUnitsResponseBody GetCurrencyUnits(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequestBody GetCurrencyUnits1) {
            gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest inValue = new gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits1;
            gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.GetCurrencyUnitsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(gyak7_jlv3dc.mnb.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest inValue = new gyak7_jlv3dc.mnb.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrentExchangeRates(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRates(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates1) {
            gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest inValue = new gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1;
            gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.GetCurrentExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest inValue = new gyak7_jlv3dc.mnb.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetDateIntervalResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetDateInterval(gyak7_jlv3dc.mnb.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public gyak7_jlv3dc.mnb.GetDateIntervalResponseBody GetDateInterval(gyak7_jlv3dc.mnb.GetDateIntervalRequestBody GetDateInterval1) {
            gyak7_jlv3dc.mnb.GetDateIntervalRequest inValue = new gyak7_jlv3dc.mnb.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval1;
            gyak7_jlv3dc.mnb.GetDateIntervalResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.GetDateIntervalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetDateIntervalResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetDateIntervalAsync(gyak7_jlv3dc.mnb.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetDateIntervalResponse> GetDateIntervalAsync(gyak7_jlv3dc.mnb.GetDateIntervalRequestBody GetDateInterval) {
            gyak7_jlv3dc.mnb.GetDateIntervalRequest inValue = new gyak7_jlv3dc.mnb.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetExchangeRatesResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetExchangeRates(gyak7_jlv3dc.mnb.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public gyak7_jlv3dc.mnb.GetExchangeRatesResponseBody GetExchangeRates(gyak7_jlv3dc.mnb.GetExchangeRatesRequestBody GetExchangeRates1) {
            gyak7_jlv3dc.mnb.GetExchangeRatesRequest inValue = new gyak7_jlv3dc.mnb.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates1;
            gyak7_jlv3dc.mnb.GetExchangeRatesResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.GetExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetExchangeRatesResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetExchangeRatesAsync(gyak7_jlv3dc.mnb.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetExchangeRatesResponse> GetExchangeRatesAsync(gyak7_jlv3dc.mnb.GetExchangeRatesRequestBody GetExchangeRates) {
            gyak7_jlv3dc.mnb.GetExchangeRatesRequest inValue = new gyak7_jlv3dc.mnb.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gyak7_jlv3dc.mnb.GetInfoResponse gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetInfo(gyak7_jlv3dc.mnb.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public gyak7_jlv3dc.mnb.GetInfoResponseBody GetInfo(gyak7_jlv3dc.mnb.GetInfoRequestBody GetInfo1) {
            gyak7_jlv3dc.mnb.GetInfoRequest inValue = new gyak7_jlv3dc.mnb.GetInfoRequest();
            inValue.GetInfo = GetInfo1;
            gyak7_jlv3dc.mnb.GetInfoResponse retVal = ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetInfoResponse> gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap.GetInfoAsync(gyak7_jlv3dc.mnb.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<gyak7_jlv3dc.mnb.GetInfoResponse> GetInfoAsync(gyak7_jlv3dc.mnb.GetInfoRequestBody GetInfo) {
            gyak7_jlv3dc.mnb.GetInfoRequest inValue = new gyak7_jlv3dc.mnb.GetInfoRequest();
            inValue.GetInfo = GetInfo;
            return ((gyak7_jlv3dc.mnb.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
    }
}
